// src/pages/Privacy.jsx

import React from 'react';
import { motion } from 'framer-motion';
import { FaLock, FaUserShield, FaServer, FaHandshake, FaQuestionCircle } from 'react-icons/fa';
import AccordionItem from '../Components/AccordionItem'; // Make sure this path is correct

const Privacy = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-indigo-800 font-sans text-white overflow-x-hidden">
      
      {/* --- HERO SECTION (No Changes) --- */}
      <section className="relative w-full max-w-6xl mx-auto px-6 md:px-12 py-20 text-center md:text-left">
        <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="font-bold text-4xl sm:text-5xl md:text-7xl text-white"
        >
            Privacy Policy
        </motion.h1>
        <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="mt-6 text-lg md:text-xl text-gray-200 max-w-3xl"
        >
            Your privacy is foundational to our technology. We are committed to transparency in how we handle and protect your data.
        </motion.p>
      </section>

      {/* --- REFINED MAIN CONTENT SECTION --- */}
      <section className="w-full max-w-6xl mx-auto px-6 md:px-12 py-20">
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.1 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          // ALIGNMENT: Padding removed from the card itself for edge-to-edge internal content
          className="bg-white/5 backdrop-blur-xl shadow-2xl rounded-2xl border border-white/10 overflow-hidden"
        >
          {/* Introduction block with its own consistent padding */}
          <div className="p-8 border-b border-white/10">
            <p className="text-gray-200 text-lg leading-relaxed">
              This Privacy Policy describes how TensorGo Inc. ("TensorGo", "we", "us", or "our") collects, uses, and discloses your information in connection with your use of our Go-X application and related services.
            </p>
          </div>
          
          {/* Interactive Accordion Items using the refined component */}
          <AccordionItem title="Information We Collect" icon={<FaServer size={22} />} defaultOpen={true}>
              <p>We collect information in several ways to provide and improve our Service:</p>
              <h3>Information You Provide</h3>
              <ul>
                <li><strong>Account Information:</strong> Name, email, company, and password.</li>
                <li><strong>Payment Information:</strong> Processed securely by our third-party payment processors. We do not store this on our servers.</li>
              </ul>
              <h3>Data Generated by the Service</h3>
              <ul>
                <li><strong>Meeting Content:</strong> Audio and video from your meetings are processed for analysis.</li>
                <li><strong>Analytical Insights:</strong> AI-generated data like transcriptions, sentiment, and voice intonation.</li>
              </ul>
          </AccordionItem>

          <AccordionItem title="How We Use Your Information" icon={<FaHandshake size={22} />}>
            <p>Your data is used solely to enhance your experience and improve our product:</p>
            <ul>
              <li>To provide, maintain, and improve the Service.</li>
              <li>To enhance our AI models using anonymized and aggregated data only.</li>
              <li>To communicate with you, including sending service notifications and support responses.</li>
            </ul>
          </AccordionItem>

          <AccordionItem title="Data Security & Protection" icon={<FaLock size={22} />}>
            <p>We implement industry-leading security measures to protect your data:</p>
            <ul>
              <li><strong>Encryption:</strong> Data is encrypted in transit (TLS) and at rest (AES-256).</li>
              <li><strong>Access Controls:</strong> Strict access controls ensure only authorized personnel can access user data.</li>
              <li><strong>Regular Audits:</strong> We undergo regular security audits to maintain compliance with standards like SOC 2 and GDPR.</li>
            </ul>
          </AccordionItem>

          <AccordionItem title="Your Rights & Controls" icon={<FaUserShield size={22} />}>
            <p>You have control over your personal data and can exercise your rights at any time:</p>
            <ul>
              <li>The right to access and receive a copy of your personal data.</li>
              <li>The right to correct any inaccurate information.</li>
              <li>The "Right to be Forgotten" to request the deletion of your account.</li>
            </ul>
            <p>To make a request, contact our privacy team at: <a href="mailto:info@tensorgo.com">info@tensorgo.com</a>.</p>
          </AccordionItem>
        </motion.div>
      </section>
    </div>
  );
};

export default Privacy;